name: Producer CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.py'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.py'

jobs:
  editorconfig:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
  linter:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: pip install black flake8

      - name: flake8 Lint
        uses: py-actions/flake8@v2
  deploy:
    needs: [editorconfig,linter]
    runs-on: ubuntu-latest

    steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        dockerfilePath: Dockerfile_producer
        acrName: mojikontenjeri
        containerAppName: producer-app
        resourceGroup: fervjestina
